public class SimpleClass {

    // Method to greet with a custom message
    public static void greet(String name) {
        System.debug('Hello, ' + name + '!'); 
    }

    // Method to calculate the sum of two numbers
    public static Integer addNumbers(Integer num1, Integer num2) {
        System.debug('MAnan');
        System.debug('andbkh');
        return num1 + num2;
    }

    // Method to check if a number is even
    public static Boolean isEven(Integer num) {
        return Math.mod(num, 2) == 0; 
    }
}

