name: Auto_Deploy_To_Staging_Org
on:
  pull_request:
    branches: [staging]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_to_staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: prepare_deploy_data to staging
      shell: bash
      run: |
        echo ${{ secrets.SFDX_AUTH_URL}} > ./SFDC_SUREBIRD_STAG_AUTH_URL.txt
        echo "files_to_deploy=$(git --no-pager diff --name-only --diff-filter=d origin/${{ github.base_ref }} -- force-app | tr '\n' ',' | sed 's/,/, /g' | sed 's/\(.*\),/\1 /')" >> $GITHUB_ENV
    - name: authenticate_to_staging
      # original repo forcedotcom/salesforcedx-actions@master
      uses: marcelblijleven/salesforcedx-actions@master
      with:
        args: force:auth:sfdxurl:store --sfdx-url-file=./SFDC_SUREBIRD_STAG_AUTH_URL.txt --alias=staging
    - name: deploy_files to staging
      # original repo forcedotcom/salesforcedx-actions@master
      uses: marcelblijleven/salesforcedx-actions@master
      with:
        args: 'force:source:deploy -c -p ''"${{ env.files_to_deploy }}"'' -l RunSpecifiedTests -r SimpleClassTest -u ${{ secrets.USERNAME }}'
       # args: 'force:source:deploy -c -p ''"${{ env.files_to_deploy }}"'' -u ${{ secrets.USERNAME }} -l RunLocalTests'
    - run: $([ $? -eq 0 ]  || exit 1)