name: Auto Deploy to Staging Org

on:
  pull_request:
    branches: [staging]

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.2
      
      - run: git fetch --prune --unshallow

      - name: Prepare Deploy Data for Staging
        shell: bash
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > ./SFDC_SUREBIRD_STAG_AUTH_URL.txt
          echo "files_to_deploy=$(git --no-pager diff --name-only --diff-filter=d origin/${{ github.base_ref }} -- force-app | tr '\n' ',' | sed 's/,/, /g' | sed 's/\(.*\),/\1 /')" >> $GITHUB_ENV
      
      - name: Authenticate to Staging
        uses: marcelblijleven/salesforcedx-actions@master
        with:
          args: force:auth:sfdxurl:store --sfdx-url-file=./SFDC_SUREBIRD_STAG_AUTH_URL.txt --alias=staging

      - name: Deploy Files to Staging
        uses: marcelblijleven/salesforcedx-actions@master
        with:
          args: 'force:source:deploy -c -p ''"${{ env.files_to_deploy }}"'' -u ${{ secrets.USERNAME }} -l RunSpecifiedTests -r SimpleClassTest'
        
      
        # uses: marcelblijleven/salesforcedx-actions@master
        # with:
        #   args: 'force:source:deploy -c -p "${{ env.files_to_deploy }}" -u ${{ secrets.USERNAME }} -l RunSpecifiedTests -r SimpleClassTest'

       #   args: 'force:source:deploy -c -p "${{ env.files_to_deploy }}" -u ${{ secrets.USERNAME }} -l RunLocalTests'
      
      - run: $([ $? -eq 0 ] || exit 1)
